version: "3"

services:

  app:
    build: .
    # image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - .:/src/
    env_file:
      - .env
    working_dir:  /src 
    command: python3  main.py queries.json
    shm_size: 2gb
    networks:  # Añade esta sección
      - mongo_default

networks:  # Asegúrate de que esta sección esté en tu archivo
  mongo_default:
    external: true
